### ISSUE TITLE
is randomUint8Array really necessary?

### ISSUE THREAD

**Issue by roccomuso** [ebceu4/waves-crypto#8]
This https://github.com/ebceu4/waves-crypto/blob/master/src/index.ts#L174 wouldn't allow to write unit tests. Beause generated signature always changes.
Is it really necessary?

**Comment by siemarell** [comment]
Yes, it is required by math behind elliptic cryptography. Otherwise you could derive secret key from signature

**Comment by roccomuso** [comment]
Are you sure? Can you show an example?

**Comment by siemarell** [comment]
I wont dive deep into the math behind it (because it would require a lot of time from my side), but long story short, you need to solve 3 or 4 equations to get signature. These equations have 2 variables: your private key and some arbitrary number. If you will use the same arbitrary number (lets name it 'K') for signing two different pieces of information, then attacker could could construct two equations: one for first signature and one for the second. Since K is equal he could solve it and get second variable, which is secret key. I hope you got general idea. [Here](https://andrea.corbellini.name/2015/05/17/elliptic-curve-cryptography-a-gentle-introduction/) is the link to the article I used to learn elliptic curve crypto

**Comment by roccomuso** [comment]
Thanks for explanation! :+1: But why here is marked as optional https://github.com/wavesplatform/waves-signature-generator/blob/master/src/libs/axlsign.ts#L1207 ?

**Comment by siemarell** [comment]
Honestly, I cannot answer this question since I'm not the author of the **axlsign**. My expertise ends with the article I've shared with you.
